"""The shared, GIVEN grading harness for the exercise notebooks.

Every exercise (``exercises/q01_activations.ipynb`` … ``q04_learnable_activations.ipynb``)
grades itself the same way: **compare the gradients the engine computed with
``backward()`` against finite differences**. Finite differences know nothing about
the engine — they only evaluate the forward function twice — so agreement is real
evidence that your ``forward`` (and, in Exercise 01, your hand-written
``_backward``) is correct.

Two entry points, one per kind of exercise:

- :func:`gradient_check` — for an ``nn.Module`` you wrote a ``forward`` for
  (Exercises 02, 03, 04). Checks the input *and* every parameter.
- :func:`check_equation` — for a plain expression built from tensor leaves
  (Exercise 01, where the graded object is an activation, not a layer).

Both build on :func:`numeric_gradient`, which is identical in spirit to
``test/test_engine.py::numeric_gradient``. You do not edit this file.
"""

from __future__ import annotations

from typing import Callable, Sequence, Tuple

import numpy as np

from bert_cpu import engine as cpu
from bert_cpu import nn


def numeric_gradient(f: Callable[[], float], x: np.ndarray, eps: float = 1e-6) -> np.ndarray:
    """Central-difference gradient of a scalar ``f()`` w.r.t. the array ``x``.

    It knows nothing about the engine, so agreeing with ``backward()`` is real
    evidence the forward pass is correct. ``f`` must re-read ``x`` (the same array
    object we perturb) on every call.
    """
    grad = np.zeros_like(x)
    it = np.nditer(x, flags=["multi_index"])
    while not it.finished:
        i = it.multi_index
        original = x[i]
        x[i] = original + eps
        plus = f()
        x[i] = original - eps
        minus = f()
        x[i] = original
        grad[i] = (plus - minus) / (2.0 * eps)
        it.iternext()
    return grad


def gradient_check(layer: nn.Module, x: cpu.Tensor, target: cpu.Tensor) -> float:
    """Backward() vs finite differences for ``loss = mean((layer(x) - target)**2)``.

    Returns the largest absolute mismatch over the input and every parameter.
    """
    def loss() -> cpu.Tensor:
        return ((layer(x) - target) ** 2).mean()

    for t in (x, *layer.parameters()):
        t.zero_grad()
    loss().backward()

    worst = 0.0
    for name, t in [("x", x), *layer.named_parameters()]:
        numeric = numeric_gradient(lambda: float(loss().data), t.data)
        err = float(np.max(np.abs(numeric - t.grad)))
        worst = max(worst, err)
        print(f"    {name:16s} max|analytic - numeric| = {err:.2e}")
    return worst


def check_equation(
    name: str,
    fn: Callable[..., cpu.Tensor],
    specs: Sequence[Tuple[str, Tuple[int, ...]]],
    tensor_cls=cpu.Tensor,
    seed: int = 0,
) -> float:
    """Backward() vs finite differences for a scalar *expression*, not a layer.

    ``specs`` names the leaves and their shapes, e.g. ``[("x", (4, 1))]``; each is
    filled with random values and fed to ``fn`` in order. ``tensor_cls`` is the
    class the leaves are built with — Exercise 01 passes its own ``ExTensor`` so
    the extra activations are available on them.

    Returns the largest absolute mismatch over every leaf.
    """
    cpu.set_seed(seed)
    leaves = [tensor_cls(np.random.randn(*shape)) for _, shape in specs]

    def value() -> float:
        return float(fn(*leaves).data)

    for t in leaves:
        t.zero_grad()
    fn(*leaves).backward()

    print(f"  {name}")
    worst = 0.0
    for (leaf_name, _), t in zip(specs, leaves):
        numeric = numeric_gradient(value, t.data)
        err = float(np.max(np.abs(numeric - t.grad)))
        worst = max(worst, err)
        print(f"    d/d{leaf_name:<13s} max|analytic - numeric| = {err:.2e}")
    print(f"    -> {'PASS' if worst < 1e-5 else 'FAIL'} (worst {worst:.2e})\n")
    return worst


def report(all_ok: bool, subject: str = "layers") -> None:
    """One closing line for a grading cell."""
    print(f"All {subject} correct — and you wrote no backward pass!"
          if all_ok else f"Some {subject} are off (or skipped); revisit their forward().")
